# Generated by Django 5.0 on 2023-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='custom_usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
