# Generated by Django 5.0 on 2023-12-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_usersubscription_custom_usage_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='custom_usage_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
